name: celestial_lingo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.4.10
  http: ^1.2.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.4


dev_dependencies:
  build_runner: ^2.4.8
  custom_lint:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  pedantic_mono:
  riverpod_generator: ^2.3.11
  riverpod_lint:


flutter:
  uses-material-design: true

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch --delete-conflicting-outputs
  android: flutter build apk --release
  genereate_json: ./tools/pkl eval ./dart_defines/develop.pkl --format json --output-path ./dart_defines/develop.json && sed -i '' 's/\\n/\\\\n/g' ./dart_defines/develop.json